---
title: "Grading Policy"
---

TO BE FINALISED

- Quizzes (36%): Three quizzes of 12% each. These are held in the exam 1, 2, 3 slots.

- Assignments (32%): 
    - Four assignments of ~8% each. 
    - Followed by a viva. 
    - Total number of groups in the course would be <=20. Depending on class size, the groups would be of 2 or 3 students.
    - The assignments would be graded on the basis of the following rubric:
        - 50%: Correctness of the code
        - 25%: Code quality
        - 25%: Presentation/Conceptual understanding
    - You get one week to complete each assignment.
    - Tentative schedule:
        - Assignment 1: 10 August (due 18 August)
        - Assignment 2: 21 August (due 28 August)
        - Assignment 3: 14 September (due 21 September)
        - ~~Assignment 4: 30 October (due 6 November)~~ Assignment 4: 28 October (due 8 November)

- Project (27%): The number of project groups would be <=10. Depending on the class size, the groups would be of 3-5 students. 
    - Tentative schedule:
        - Presentation I: 6 October (10%)
        - Final Project presentation: ~~22 November~~ 17 Nov (12%)
        - Final report: ~~24 November~~ 20 Nov (5%)

- Interactive article (5%): Create a Streamlit or similar interactive article for concept explanation (due 15 November)
