---
title: "ES 654 Machine Learning"
---

### Summary

* Instructor: Nipun Batra (nipun.batra@iitgn.ac.in)
* Teaching Assistants: Zeel B Patel, Shriraj Sawant, Shrutimoy, Sarth Dubey, Hitarth Gandhi, Saagar Parikh, Eshan Gujarathi, Gautam Vashishta, Aadesh Desai
* Course Timings: Tuesday, Thursday 330-450 PM IST in 1/101
* [Slack Invite](https://join.slack.com/t/es654-2022/shared_invite/zt-1mgeh688j-Wynv7_s_0n2_FaSu7kbUWg)



### Pre-requisites:

*   Good experience in Python programming
*   Probability
*   Linear Algebra

Course preparation: Students are encouraged to study some of the following to refresh their understanding of some of the prerequisities before the course formally begins.  

*  First four chapters of the [Python Data Science handbook](https://jakevdp.github.io/PythonDataScienceHandbook/)
*   [Some material on Linear Algebra](https://machinelearningmastery.com/linear-algebra-machine-learning/)
*   [Khan academy course on Stats and Probability](https://www.khanacademy.org/math/statistics-probability)



### Reference textbooks:

1.  Gareth James, Daniela Witten, Trevor Hastie and Robert Tibshirani. [An Introduction to Statistical Learning with Applications in R](http://www-bcf.usc.edu/~gareth/ISL/)
2.  Christopher Bishop. Pattern Recognition and Machine Learning. Springer, 2006.[\[Freely available online\]](https://www.microsoft.com/en-us/research/uploads/prod/2006/01/Bishop-Pattern-Recognition-and-Machine-Learning-2006.pdf)
3.  Friedman J, Hastie T, Tibshirani R. The elements of statistical learning. New York, NY, USA:: Springer series in statistics; 2001.[\[Freely available online\]](https://web.stanford.edu/~hastie/Papers/ESLII.pdf)
4.  Duda RO, Hart PE, Stork DG. Pattern classification. John Wiley & Sons; 2012 Nov 9.
5.  Mitchell TM. Machine learning. 1997. Burr Ridge, IL: McGraw Hill. 1997;45(37):870-7.
6.  Murphy, K. Machine Learning: A Probabilistic Perspective. MIT Press
7.  Goodfellow I, Bengio Y, Courville A, Bengio Y. Deep learning. Cambridge: MIT press; 2016 Nov 18.[\[Freely available online\]](https://www.deeplearningbook.org/)



### Some other ML courses

1.  [NPTEL course by Balaram Ravindran](https://www.youtube.com/watch?v=r4sgKrRL2Ys&list=PL1xHD4vteKYVpaIiy295pg6_SY5qznc77)
2.  [CMU course by Tom Mitchell and Maria-Florina Balcan](http://www.cs.cmu.edu/~ninamf/courses/601sp15/lectures.shtml)
3.  [Coursera ML course by Andrew Ng](https://www.coursera.org/learn/machine-learning)
4.  [FAST.ai course on ML](https://course.fast.ai/ml)
5.  [Practical deep learning for coders by FAST.ai](https://course.fast.ai/index.html)
6.  [Course by Alex Ihler, UCI](http://sli.ics.uci.edu/Classes/2015W-273a)

