---
title: "Schedule"
---

The YouTube playlist is linked [here](https://www.youtube.com/watch?v=UCYaVS9_jGU&list=PLftoLyLEwECBEJyfRBJoSBd0UaTjEcs3I).
The page containing the notebooks is linked [here](notebooks/index.qmd).

|Lecture #|Date|Topic| Reading|
|:---:|:---:|:---|:---|
|1| Aug 3| Introduction and Logistics [[Slides](lectures/introduction.pdf)], [[YouTube](https://www.youtube.com/watch?v=UCYaVS9_jGU)]|
|2| Aug 7| Bayes Rule for ML [[Slides](lectures/Bayes-ML.pdf)], [[YouTube](https://www.youtube.com/watch?v=d1v7SeXAWl8)], [[Notebook](notebooks/bayes-librarian.ipynb)]|
|3| Aug 10| Distributions, Sampling, Likelihood [[Slides](lectures/MLE.pdf)][[Youtube](https://www.youtube.com/watch?v=9zZqgZj3RlA)] [[Notebook on Distributions](notebooks/distributions.ipynb)], [[Notebook on likelihood](notebooks/bayes-librarian.ipynb)], [[Notebook on MLE](notebooks/mle-univariate.ipynb)]|
|4| Aug 14| Maximum Likelihood Estimation (Univariate Normal) [[Slides](lectures/MLE.pdf)] [[Revision on bias/variance of estimators in context of ML prediction](https://nipunbatra.github.io/ml2023/lectures/cross-validation.pdf)], [[SGD is unbiased](https://florian.github.io/estimators/)], [[Notebook on likelihood](notebooks/bayes-librarian.ipynb)], [[Notebook on MLE](notebooks/mle-univariate.ipynb)], [[Notebook on biased estimators](notebooks/biased-mle-normal.ipynb)], [[Youtube](https://www.youtube.com/watch?v=qxeceHW3Ab4)]|
|5| Aug 17| MLE for linear and logistic regression [[Slides](https://github.com/nipunbatra/pml-teaching/blob/master/slides/MLE_Lin_Log_Reg.pdf)], [[Notebook](https://github.com/nipunbatra/pml-teaching/blob/master/notebooks/log-likelihood-linreg.ipynb)], [[Youtube](https://www.youtube.com/watch?v=yuLFyp9NvDU)]|
|6| Aug 21| MAP for coin toss, Multivariate Normal [[Slides](https://github.com/nipunbatra/pml-teaching/blob/master/slides/map.pdf)], [[Notebook on MAP](https://github.com/nipunbatra/pml-teaching/blob/master/notebooks/MAP.ipynb)], [[Youtube](https://www.youtube.com/watch?v=Z8P2soJi5jg)]|
|7| Aug 24| Bayesian Linear Regression [[Slides](https://github.com/nipunbatra/pml-teaching/blob/master/slides/mvn-blr.pdf)], [[Notebook MVN](https://github.com/nipunbatra/pml-teaching/blob/master/notebooks/visualise_normal.ipynb)], [[Youtube](https://www.youtube.com/watch?v=GwObokEUbBU)]|
|8| Aug 28| Laplace Appoximation [[Slides](https://github.com/nipunbatra/pml-teaching/blob/master/slides/laplace-approximation.pdf)], [[Notebook](https://github.com/nipunbatra/pml-teaching/blob/master/notebooks/laplace-approx.ipynb)], Calculus [[Slides](https://github.com/nipunbatra/pml-teaching/blob/master/slides/calculus-terms.pdf)], [[Notebook](https://github.com/nipunbatra/pml-teaching/blob/master/notebooks/calculus.ipynb)] [[Youtube](https://www.youtube.com/watch?v=7sYN15nrgZY)]|
|9| Aug 31| Monte Carlo Sampling [[Slides](https://github.com/nipunbatra/pml-teaching/blob/master/slides/Sampling-1.pdf)], [[Notebooks]], [[Youtube](https://www.youtube.com/watch?v=eCTCFI98Fl0)]|
|10| Sep 11| Monte Carlo Sampling and Sampling from common distributions [[Slides](https://github.com/nipunbatra/pml-teaching/blob/master/slides/Sampling-1.pdf)], [[Notebooks]], [[YouTube](https://www.youtube.com/watch?v=Bl2VP1jl3SA&list=PLftoLyLEwECBEJyfRBJoSBd0UaTjEcs3I&index=10)]|
|11| Sep 14| Neural Networks uncertainty [[Notebook](https://github.com/nipunbatra/pml-teaching/blob/master/notebooks/nn-variants-final.ipynb)], [[YouTube](https://www.youtube.com/watch?v=hKgcZuAdgnM)]|
|12| Sep 18| Rejection and Importance Sampling [[Slides](https://github.com/nipunbatra/pml-teaching/blob/master/slides/Sampling-2.pdf)] [[Notebook](https://github.com/nipunbatra/pml-teaching/blob/master/notebooks/rejection-sampling-importance-sampling.ipynb)] [[YouTube](https://www.youtube.com/watch?v=_xWL9AvYNlE&feature=youtu.be)]|
|13| Sep 21| Practical MCMC [[Notebook](https://github.com/nipunbatra/pml-teaching/blob/master/notebooks/mcmc-hamiltorch.ipynb)] [[Youtube](https://www.youtube.com/watch?v=GEGTRKBX-20)]|
14| Sep 25| MCMC theory [[Slides 1 on Markov Chain](https://github.com/nipunbatra/pml-teaching/blob/master/slides/hmm.pdf)], [[Slides on MCMC](https://github.com/nipunbatra/pml-teaching/blob/master/slides/MCMC.pdf)] [[Markov Chain notebook](https://github.com/nipunbatra/pml-teaching/blob/master/notebooks/markov-chain.ipynb)]|
15| Oct 5| Calibration [[Youtube](https://www.youtube.com/watch?v=1YLYuRFjdqU)], [[Notebook](https://github.com/nipunbatra/pml-teaching/blob/master/notebooks/reliability.ipynb)], [[Tutorial on Calibration](https://classifier-calibration.github.io)]|
16| Oct 9| MC Dropout and Deep Ensemble [[Youtube](https://www.youtube.com/watch?v=jYjLuFiTpck)], [[Notebook](https://github.com/nipunbatra/pml-teaching/blob/master/notebooks/monte-carlo-dropout.ipynb)]|
17| Oct 16| Hierarchical Models, [[Notebook](https://github.com/nipunbatra/pml-teaching/blob/master/notebooks/hierarchical_lr_numpyro.ipynb)], [[YouTube](https://www.youtube.com/watch?v=FFSk8Z1FDxw)]|
18| Oct 19| Meta learning: Hypernets and Neural Processes, [[Notebook](https://github.com/nipunbatra/pml-teaching/blob/master/notebooks/hypernet-np.ipynb)], [[YouTube](https://www.youtube.com/watch?v=V_pYGbAArMk&list=PLftoLyLEwECBEJyfRBJoSBd0UaTjEcs3I&index=18)]|
19| Oct 30| Meta Learning: SIREN, Coordinate Network, Hypernets, Neural Processes [[Notebook](https://github.com/nipunbatra/pml-teaching/blob/master/notebooks/siren.ipynb)], [[YouTube](https://www.youtube.com/watch?v=xh8l0Us0al0)]|
20 | Nov 2| Self-supervised learning [[Notebook](https://github.com/nipunbatra/pml-teaching/blob/master/notebooks/ssl.ipynb)], [[YouTube](https://www.youtube.com/watch?v=MZ07_GG3JD4)], [[Survey article on SSLs](https://amitness.com/2020/02/illustrated-self-supervised-learning/)]|
21| Nov 6| Active Learning [[Notebook](https://github.com/nipunbatra/pml-teaching/blob/master/notebooks/active-learning.ipynb)], [[Interactive article](https://patel-zeel.github.io/active-learning-visualization/)], [[YouTube](https://www.youtube.com/watch?v=4Qeb_0pW9No)], [[Survey Article](https://burrsettles.com/pub/settles.activelearning.pdf)], [[Article on Deep Active Learning](https://jacobgil.github.io/deeplearning/activelearning)]|
22| Nov 9| Bayesian Optimisation [[Notebook 1 on Motivation](https://github.com/nipunbatra/pml-teaching/blob/master/notebooks/bayesopt-motivation.ipynb)], [[Notebook 2 on implementation from scratch](https://github.com/nipunbatra/pml-teaching/blob/master/notebooks/bayesopt.ipynb)], [[YouTube](https://www.youtube.com/watch?v=RUFdlr0KWWw)], [[Distill.Pub article](https://distill.pub/2020/bayesian-optimization/)], [[Other reference](https://ekamperi.github.io/machine%20learning/2021/06/11/acquisition-functions.html)]|
23| Nov 13| KL divergence, Variational Inference, MC sampling, Reparameterisation [[Notebook](https://github.com/nipunbatra/pml-teaching/blob/master/notebooks/variational-inference.ipynb)], [[YouTube](https://www.youtube.com/watch?v=x5JPd-bgfhc)]|
24| Nov 16| Variational Inference-II: ELBO, Coin Toss [[Notebook](https://github.com/nipunbatra/pml-teaching/blob/master/notebooks/variational-inference.ipynb)][[YouTube](https://www.youtube.com/watch?v=fQ8D0-tTCBU)]|
25| Nov 20| Variational Inference-III: Variational Autoencoders [[Notebook](https://github.com/nipunbatra/pml-teaching/blob/master/notebooks/vae.ipynb)], [[YouTube](https://www.youtube.com/watch?v=fQ8D0-tTCBU)], [[Article on AutoEncoder variants](https://lilianweng.github.io/posts/2018-08-12-vae/)], [[Article on VAE (esp. Bayes rule)](https://jaan.io/what-is-variational-autoencoder-vae-tutorial/)]|
26| Nov 23| Conformal Prediction?/Neural Processes?/Gaussian Processes?|
